name: web-build

on:
  push:
    branches:
      - main
    paths: 
      - 'pipsas/**'

jobs:
  build-web:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necesario para OIDC
      contents: read   # Necesario para actions/checkout
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2

      - name: configurar aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::418272787842:role/repartidor
          aws-region: us-east-1
      
      - name: configurar flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"

      - name: Instalar dependencias
        working-directory: pipsas
        run: |
          flutter pub get
          flutter doctor -v
            
      - name: Construir Flutter Web (con logs detallados)
        working-directory: pipsas
        run: |
          flutter config --enable-web
          flutter clean
          flutter build web --release -v 2>&1 | tee build.log
            
      - name: Mostrar logs de error
        if: failure()
        run: |
          cat build.log || echo "No se encontró archivo de log"
          ls -la || echo "No se pudo listar directorio"
          pwd || echo "No se pudo obtener directorio actual"
            
      - name: Subir build web a S3
        if: success()
        working-directory: pipsas
        run: |
          aws s3 sync build/web s3://guardapipsas --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --exclude "*" \
            --include "assets/*" \
            --include "manifest.json" \
            --include "*.html" \
            --include "*.js" \
            --include "*.wasm"
      - name: Debug - confirm upload to S3
        run: echo "Upload to S3 completed"